# docker configuration for delta real estate platform

services:
  # postgresql database
  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: delta_real_estate
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d delta_real_estate"]
      interval: 30s
      timeout: 10s
      retries: 3

  # backend api
  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: postgresql://user:password@postgres:5432/delta_real_estate
      SECRET_KEY: your-production-secret-key
      CORS_ORIGINS: http://localhost:3000
      DEBUG: false
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ./backend:/app
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload

  # frontend react app
  frontend:
    build:
      context: .
      dockerfile: frontend.Dockerfile
    ports:
      - "3000:3000"
    environment:
      - VITE_API_URL=http://localhost:8000
    volumes:
      - .:/app
      - /app/node_modules
    command: npm run dev -- --host 0.0.0.0

volumes:
  postgres_data:
